### ISSUE TITLE
Syntax error on starting server 

### ISSUE THREAD

**Issue by kulturbande** [minifeed/iridium#10]
Steps to reproduce:
1. $ iridium app {name}-{another_name}
2. $ cd {name}-{another_name}
3. $ iridium server
/Users/user/.rvm/gems/ruby-1.9.3-p194/bundler/gems/iridium-825f737f87bb/lib/iridium/cli.rb:24:in `require': /Users/user/Projects/{name}-{another_name}/application.rb:1: syntax error, unexpected '-', expecting '<' or ';' or '\n' (SyntaxError)

Problem:
The Class name of the application.rb is Name-another_name (the second name after the dash is lowercase). It should be camelcased NameAnother_name. (That example lacks because there is also the underscore that can cause trouble)

Solution:
An Inflector for the dynamic class name in the application.rb

**Comment by ahawkins** [comment]
@kulturbande thanks for your detailed and accurate report! `{name}-{another_name}` is a tough case. It cannot be mapped to camel case or underscored since `name` is camel cased connected with a dash to `another_name` which is underscored. Also, your solution to translate it to `NameAnother_name` doesn't work because it doesn't blend in Ruby land.   I think raising an error is best for this case. I totally need to add some validation and other things to this command.

**Comment by muescha** [comment]
But then the error should raised at the iridium app command or it should print out a warning while the iridium app command

**Comment by muescha** [comment]
Or it should replace the '-' with a underscore "_"

**Comment by ahawkins** [comment]
Ya. I mean running the command. The command should stop you from generating
a bad app.

**Comment by kulturbande** [comment]
Sure, the example wasn't that good. In my case the dash produced the error: `iridium app foo-bar`generate the class name `Foo-bar`in the application.rb and I guess that is solvable with a kind of an inflector.
